### ISSUE TITLE
Mod causes unhandled ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by fredrikhr** [xmnovotny/VoxelTycoon-ScheduleStopwatch#3]
The mod messes up route schedules for bus-lines. Suddenly stops in the schedule disappear. Attched the log file produced.

[Player.log](https://github.com/xmnovotny/VoxelTycoon-ScheduleStopwatch/files/6673086/Player.log)

**Comment by xmnovotny** [comment]
Thanks for reporting, this is already solved in the new version of the mod. I will publish it in a few days.

**Comment by xmnovotny** [comment]
Fixed in 2.0
