### ISSUE TITLE
ZH

### ISSUE THREAD

**Issue by TheHZDev** [xmnovotny/VoxelTycoon-ScheduleStopwatch#5]
Add some Chinese translation and some of them coule be inaccurate.
{
  "schedule_stopwatch/missing_time_segment": "缺少部分路线的数据",
  "schedule_stopwatch/times_per_month": "路线周期 ({0}x 每月)",
  "schedule_stopwatch/days_hours": "{0}天 {1}小时",
  "schedule_stopwatch/hours_minutes": "{0}小时 {1}分钟",
  "schedule_stopwatch/unknown": "未知",
  "schedule_stopwatch/display_time_for_inidividual_tasks": "显示日程中各个任务的时间",
  "schedule_stopwatch/display_totaltime_in_schedule": "在载具窗口中显示总时间",
  "schedule_stopwatch/display_total_capacity": "在载具窗口中显示每月总运力",
  "schedule_stopwatch/display_individual_unloading_capacity": "显示每个任务的预期每月运入项目数量",
  "schedule_stopwatch/display_individual_loading_capacity": "显示每个任务的预期每月运出物品数量",
  "schedule_stopwatch/display_station_loading_capacity": "在载具窗口中显示预期运入物品的数量",
  "schedule_stopwatch/display_station_unloading_capacity": "在载具窗口中显示预期运出物品的数量",
  "schedule_stopwatch/settings_window_title": "运输能力估算器设置",
  "schedule_stopwatch/loaded_items_count": "运走了 {0} 个",
  "schedule_stopwatch/unloaded_items_count": "运来了 {0} 个",
  "schedule_stopwatch/estim_monthly_transf": "预计每月运送量",
  "schedule_stopwatch/estim_monthly_transf_hint": "（本车/所有同一路线车辆）",
  "schedule_stopwatch/total_transfer": "总运力",
  "schedule_stopwatch/task_times_hint": "距离上一任务的行程时间/车站滞留时间\n灰色表示时间估计",
  "schedule_stopwatch/monthly_unloaded_items": "每月预计运入量",
  "schedule_stopwatch/monthly_loaded_items": "每月预计运出量",
  "schedule_stopwatch/needed_items_to_produce": "渴求更多的商品",
  "schedule_stopwatch/needed_items_to_produce_this": "需要更多的原材料来制造它",
  "schedule_stopwatch/number_of_mines": "{0} of {1}",
  "schedule_stopwatch/no_transfers": "没有运输",
  "schedule_stopwatch/no_transfers_data": "缺少运输数据",
  "schedule_stopwatch/average_schedule_speed": "平均速度: {0} {1}",
  "schedule_stopwatch/ratio_loading_total": "装运时间占总时间的比重: {0}%",
  "schedule_stopwatch/partial": "部分的",
  "schedule_stopwatch/monthly_demand": "(月度需求)",
  "schedule_stopwatch/estimated": "(估计)",
  "schedule_stopwatch/inaccurate": "(不准确)",
  "schedule_stopwatch/add_new_demand_tooltip": "新增了一座需求建筑（实验室或是商店）",
  "schedule_stopwatch/connect_station_tooltip": "连接一个额外的站点，用于每月需求、交付和取货的总和。",
  "schedule_stopwatch/demanded_items_tooltip": "货运站范围内的商店和实验室直接需要的物品。",
  "schedule_stopwatch/needed_items_tooltip": "生产所需的物品，并在站内挑选物品。",
  "schedule_stopwatch/needed_factories_tooltip": "需要在站点内生产请求和拣配的物品的工厂数量。",
  "schedule_stopwatch/buildings_with_demand": "建筑物需求",
  "schedule_stopwatch/connected_stations": "已连接的站点",
  "schedule_stopwatch/demanded_items": "需求的物品",
  "schedule_stopwatch/needed_items": "需要更多的物品",
  "schedule_stopwatch/factories_needed": "需要更多的工厂",
  "schedule_stopwatch/logistics_2": "Logistics II",
  "schedule_stopwatch/add_building_for_demand": "新加入站点的需求建筑",
  "schedule_stopwatch/already_added": "已经被添加",
  "schedule_stopwatch/pick_store_or_lab": "满足商店或实验室的需求",
  "schedule_stopwatch/add_connected_station": "增加与之互联的车站",
  "schedule_stopwatch/pick_station": "货运站",
  "schedule_stopwatch/remove": "移除",
  "schedule_stopwatch/no_demanded_items": "没有需求物品",
  "schedule_stopwatch/calculate_unserviced_demands": "计算没有送货订单的商店所需的物品",
  "schedule_stopwatch/calculate_unserviced_demands_description": "即使尚未向商店提供服务，也计算商店需求的物品和对应工厂的生产能力。"
}

**Comment by xmnovotny** [comment]
Thanks for the translation, I will publish it in the next update today.

**Comment by xmnovotny** [comment]
Added to the mod.

**Comment by TheHZDev** [comment]
This is newer translation. I fixed some semantics error.
{
  "schedule_stopwatch/missing_time_segment": "缺少部分路线的数据",
  "schedule_stopwatch/times_per_month": "路线周期 ({0}x 每月)",
  "schedule_stopwatch/days_hours": "{0}天 {1}小时",
  "schedule_stopwatch/hours_minutes": "{0}小时 {1}分钟",
  "schedule_stopwatch/unknown": "未知",
  "schedule_stopwatch/display_time_for_inidividual_tasks": "显示日程中各个任务的时间",
  "schedule_stopwatch/display_totaltime_in_schedule": "在载具窗口中显示总时间",
  "schedule_stopwatch/display_total_capacity": "在载具窗口中显示每月总运力",
  "schedule_stopwatch/display_individual_unloading_capacity": "显示每个任务的预期每月运入项目数量",
  "schedule_stopwatch/display_individual_loading_capacity": "显示每个任务的预期每月运出物品数量",
  "schedule_stopwatch/display_station_loading_capacity": "在载具窗口中显示预期运入物品的数量",
  "schedule_stopwatch/display_station_unloading_capacity": "在载具窗口中显示预期运出物品的数量",
  "schedule_stopwatch/settings_window_title": "运输能力估算器设置",
  "schedule_stopwatch/loaded_items_count": "运走了 {0} 个",
  "schedule_stopwatch/unloaded_items_count": "运来了 {0} 个",
  "schedule_stopwatch/estim_monthly_transf": "预计每月运送量",
  "schedule_stopwatch/estim_monthly_transf_hint": "（本车/所有同一路线车辆）",
  "schedule_stopwatch/total_transfer": "总运力",
  "schedule_stopwatch/task_times_hint": "距离上一任务的行程时间/车站滞留时间\n灰色表示时间估计",
  "schedule_stopwatch/monthly_unloaded_items": "每月预计运入量",
  "schedule_stopwatch/monthly_loaded_items": "每月预计运出量",
  "schedule_stopwatch/needed_items_to_produce": "渴求更多的商品",
  "schedule_stopwatch/needed_items_to_produce_this": "需要更多的原材料来制造它",
  "schedule_stopwatch/number_of_mines": "{0} of {1}",
  "schedule_stopwatch/no_transfers": "没有运输",
  "schedule_stopwatch/no_transfers_data": "缺少运输数据",
  "schedule_stopwatch/average_schedule_speed": "平均速度: {0} {1}",
  "schedule_stopwatch/ratio_loading_total": "装运时间占总时间的比重: {0}%",
  "schedule_stopwatch/partial": "部分的",
  "schedule_stopwatch/monthly_demand": "(月度需求)",
  "schedule_stopwatch/estimated": "(估计)",
  "schedule_stopwatch/inaccurate": "(不准确)",
  "schedule_stopwatch/add_new_demand_tooltip": "将一座新的需求建筑一起计算（实验室或是商店）",
  "schedule_stopwatch/connect_station_tooltip": "连接一个额外的站点，用于计算每月需求、交付和取货的总和。",
  "schedule_stopwatch/demanded_items_tooltip": "货运站范围内的商店和实验室直接需要的物品。",
  "schedule_stopwatch/needed_items_tooltip": "生产所需的物品，并在站内挑选物品。",
  "schedule_stopwatch/needed_factories_tooltip": "需要在站点内生产请求和拣配的物品的工厂数量。",
  "schedule_stopwatch/buildings_with_demand": "建筑物需求",
  "schedule_stopwatch/connected_stations": "已连接的站点",
  "schedule_stopwatch/demanded_items": "月度物品需求",
  "schedule_stopwatch/needed_items": "满足需求的最小月度产量",
  "schedule_stopwatch/factories_needed": "满足需求的最小工厂数量",
  "schedule_stopwatch/logistics_2": "Logistics II",
  "schedule_stopwatch/add_building_for_demand": "新加入站点的需求建筑",
  "schedule_stopwatch/already_added": "已经被添加",
  "schedule_stopwatch/pick_store_or_lab": "满足商店或实验室的需求",
  "schedule_stopwatch/add_connected_station": "增加与之互联的车站",
  "schedule_stopwatch/pick_station": "货运站",
  "schedule_stopwatch/remove": "移除",
  "schedule_stopwatch/no_demanded_items": "没有需求物品",
  "schedule_stopwatch/calculate_unserviced_demands": "计算没有送货订单的商店所需的物品",
  "schedule_stopwatch/calculate_unserviced_demands_description": "即使尚未向商店提供服务，也计算商店需求的物品和对应工厂的生产能力。"
}
